from typing import Protocol, Optional, Dict, Any


class UserRepo(Protocol):
    def insertar_usuario(self, usuario: Dict) -> str:
        ...

    def obtener_usuario(self, uid: str) -> Optional[Dict]:
        ...

    def find_by_username(self, username: str) -> Optional[Dict]:
        ...


class FullRepo(UserRepo, Protocol):
    # Partidos
    def insertar_partido(self, partido: Dict) -> str: ...
    def obtener_partido(self, pid: str) -> Optional[Dict]: ...
    def update_partido(self, pid: str, patch: Dict[str, Any]) -> bool: ...

    # Apuestas
    def insertar_apuesta(self, apuesta: Dict) -> str: ...
    def obtener_apuesta(self, aid: str) -> Optional[Dict]: ...
    def get_apuestas_by_partido(self, partido_id: str) -> list: ...

    # Usuario helpers
    def update_usuario_saldo(self, uid: str, nuevo_saldo: float) -> bool: ...
    def add_apuesta_to_usuario(self, uid: str, aid: str) -> None: ...
